const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let DATA=null,heroData=null,socialPreviewData=null;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,opt={}){const r=await fetch('/api/'+path,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Não foi possível concluir.');return d}
function showAuth(id){$$('.auth-view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.login-error').forEach(e=>e.textContent='')}
$$('[data-auth]').forEach(b=>b.onclick=()=>showAuth(b.dataset.auth));$$('.show-pass').forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.target);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Mostrar':'Ocultar'});
function unlock(){document.body.classList.remove('locked')}
async function authStatus(){try{const s=await api('auth/status');if(s.authenticated){unlock();await loadData()}else if(s.hasAdmin)showAuth('loginView');else showAuth('registerView')}catch(e){$('#loginError').textContent=e.message}}
$('#registerBtn').onclick=async()=>{const b={name:$('#registerName').value.trim(),email:$('#registerEmail').value.trim(),username:$('#registerUser').value.trim(),password:$('#registerPass').value};if(b.password!==$('#registerPass2').value){$('#registerError').textContent='As duas senhas precisam ser iguais.';return}try{await api('auth/register',{method:'POST',body:JSON.stringify(b)});unlock();await loadData()}catch(e){$('#registerError').textContent=e.message}};
$('#loginBtn').onclick=async()=>{try{await api('auth/login',{method:'POST',body:JSON.stringify({key:$('#loginUser').value.trim(),password:$('#loginPass').value})});unlock();await loadData()}catch(e){$('#loginError').textContent=e.message}};$('#loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginBtn').click()});
$('#recoverBtn').onclick=()=>{$('#recoverError').textContent='Por segurança, a V7 não redefine senha apenas por e-mail. A recuperação será configurada com um provedor de e-mail na versão online.'};
$('#logoutBtn').onclick=async()=>{await api('auth/logout',{method:'POST'});location.reload()};
function openTab(id){$$('.admin-sidebar nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.admin-tab').forEach(t=>t.classList.toggle('active',t.id===id));renderAll()}
$$('.admin-sidebar nav button').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$$('.jump-tab').forEach(b=>b.onclick=()=>openTab(b.dataset.target));
function statusClass(s){return s==='Confirmado'?'confirmed':s==='Cancelado'?'cancelled':'pending'}function waMessage(b){const d=b.date.split('-').reverse().join('/');return `Olá, ${b.name}! Tudo bem? 🌿 Aqui é da Dra. Suzana Cavalcante. Seu horário para ${b.service.toLowerCase()} foi confirmado para o dia ${d}, às ${b.time}. Ficaremos felizes em receber você. Se precisar falar conosco ou tiver qualquer imprevisto, pode responder por aqui. 💚`}function waLink(b){return `https://wa.me/55${String(b.phone).replace(/\D/g,'')}?text=${encodeURIComponent(waMessage(b))}`}
function googleCalendarLink(b){const start=new Date(`${b.date}T${b.time}:00`),end=new Date(start.getTime()+3600000),fmt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z'),details=`Paciente: ${b.name}\nWhatsApp: ${b.phone}\nServiço: ${b.service}${b.notes?`\nObservações: ${b.notes}`:''}`;return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent('Consulta - '+b.name)}&dates=${fmt(start)}/${fmt(end)}&details=${encodeURIComponent(details)}&location=${encodeURIComponent('R. José Bonifácio, 1050 - Bloco 2, sala 416 - Todos os Santos, Rio de Janeiro - RJ')}`}
function bookingHTML(b,actions=false){return `<div class="booking-item"><div class="booking-main"><strong>${b.time} • ${esc(b.name)}</strong><span>${b.date.split('-').reverse().join('/')} • ${esc(b.service)}</span>${b.notes?`<small>Observação: ${esc(b.notes)}</small>`:''}${actions?`<div class="booking-actions">${b.status==='Pendente'?`<button class="mini-action approve" onclick="setStatus(${b.id},'Confirmado')">✓ Aprovar consulta</button><a class="mini-action whatsapp-action" href="${waLink(b)}" target="_blank">Confirmar via WhatsApp</a><a class="mini-action calendar-action" href="${googleCalendarLink(b)}" target="_blank">Adicionar ao Google Agenda</a><button class="mini-action" onclick="setStatus(${b.id},'Cancelado')">✕ Recusar</button>`:''}${b.status==='Confirmado'?`<a class="mini-action whatsapp-action" href="${waLink(b)}" target="_blank">Confirmar via WhatsApp</a><a class="mini-action calendar-action" href="${googleCalendarLink(b)}" target="_blank">Adicionar ao Google Agenda</a><button class="mini-action" onclick="setStatus(${b.id},'Cancelado')">Cancelar</button>`:''}</div>`:''}</div><div class="booking-meta"><span class="status-pill status-${statusClass(b.status)}">${b.status}</span><span>${esc(b.phone)}</span></div></div>`}
window.setStatus=async(id,status)=>{try{await api('admin/bookings/'+id,{method:'PATCH',body:JSON.stringify({status})});await loadData()}catch(e){alert(e.message)}};
const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];function renderAv(){const av=DATA.availability||{};$('#availabilityEditor').innerHTML=[1,2,3,4,5,6,0].map(d=>{const x=av[d]||{on:false,start:'09:00',end:'18:00'};return `<div class="availability-day" data-day="${d}"><strong>${days[d]}</strong><label class="time-label">Começo<input class="start" type="time" value="${x.start}"></label><label class="time-label">Término<input class="end" type="time" value="${x.end}"></label><label class="day-toggle"><input class="on" type="checkbox" ${x.on?'checked':''}> Atender neste dia</label></div>`}).join('')}
async function saveSettings(payload,msg){try{await api('admin/settings',{method:'PUT',body:JSON.stringify(payload)});await loadData();alert(msg)}catch(e){alert(e.message)}}
$('#saveAvailability').onclick=()=>{const av={};$$('.availability-day').forEach(r=>av[r.dataset.day]={on:r.querySelector('.on').checked,start:r.querySelector('.start').value,end:r.querySelector('.end').value});saveSettings({availability:av},'Pronto, Dra. Suzana! Seus horários foram salvos no banco.')};
function loadPromo(){const p=DATA.promo||{};$('#promoActive').checked=!!p.active;$('#promoTitleInput').value=p.title||'';$('#promoDescInput').value=p.description||'';$('#showPrice').checked=!!p.showPrice;$('#oldPriceInput').value=p.oldPrice||'';$('#priceInput').value=p.price||''}$('#savePromo').onclick=()=>saveSettings({promo:{active:$('#promoActive').checked,title:$('#promoTitleInput').value,description:$('#promoDescInput').value,showPrice:$('#showPrice').checked,oldPrice:$('#oldPriceInput').value,price:$('#priceInput').value}},'Pronto, Dra. Suzana! A promoção foi atualizada.');
function resizeImage(file,max=1200,quality=.78){return new Promise((resolve,reject)=>{const img=new Image(),reader=new FileReader();reader.onload=()=>img.src=reader.result;reader.onerror=reject;img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',quality))};reader.readAsDataURL(file)})}
$('#heroUpload').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;heroData=await resizeImage(f);$('#heroPreview').src=heroData});$('#heroPosition').onchange=()=>$('#heroPreview').style.objectPosition=$('#heroPosition').value+' center';$('#saveAppearance').onclick=()=>saveSettings({appearance:{heroImage:heroData??DATA.appearance?.heroImage??null,heroPosition:$('#heroPosition').value}},'Pronto, Dra. Suzana! A foto da capa foi salva no banco.');$('#resetHero').onclick=()=>{heroData=null;saveSettings({appearance:{heroImage:null,heroPosition:'center'}},'A foto inicial foi restaurada.')};
function socialPreviewImage(file){
 return new Promise((resolve,reject)=>{
  const img=new Image(),reader=new FileReader();
  reader.onerror=reject;
  reader.onload=()=>img.src=reader.result;
  img.onload=()=>{
   const c=document.createElement('canvas');c.width=1200;c.height=630;
   const ctx=c.getContext('2d');ctx.fillStyle='#073d2b';ctx.fillRect(0,0,1200,630);
   const scale=Math.min(1080/img.width,570/img.height);
   const w=img.width*scale,h=img.height*scale,x=(1200-w)/2,y=(630-h)/2;
   ctx.drawImage(img,x,y,w,h);
   resolve(c.toDataURL('image/jpeg',.9));
  };
  reader.readAsDataURL(file);
 });
}
$('#socialPreviewUpload')?.addEventListener('change',async e=>{
 const f=e.target.files?.[0];if(!f)return;
 socialPreviewData=await socialPreviewImage(f);
 $('#socialPreviewAdmin').src=socialPreviewData;
});
$('#saveSocialPreview')?.addEventListener('click',()=>saveSettings(
 {appearance:{...(DATA.appearance||{}),socialPreview:socialPreviewData??DATA.appearance?.socialPreview??null}},
 'Imagem de compartilhamento salva. O WhatsApp pode levar alguns minutos para atualizar a prévia.'
));
$('#resetSocialPreview')?.addEventListener('click',()=>{
 socialPreviewData=null;
 saveSettings({appearance:{...(DATA.appearance||{}),socialPreview:null}},'Imagem inicial de compartilhamento restaurada.');
 $('#socialPreviewAdmin').src='/api/social-preview?reset='+Date.now();
});

function loadAbout(){const a=DATA.about||{};$('#aboutTitleInput').value=a.title||'';$('#aboutTextInput').value=a.text||''}$('#saveAbout').onclick=()=>saveSettings({about:{title:$('#aboutTitleInput').value,text:$('#aboutTextInput').value}},'Pronto, Dra. Suzana! Sua história foi atualizada.');
window.reviewStatus=async(id,status)=>{try{await api('admin/reviews/'+id,{method:'PATCH',body:JSON.stringify({status})});await loadData()}catch(e){alert(e.message)}};function reviewHTML(r){return `<div class="review-admin-item"><div class="review-admin-person">${r.photo?`<img src="${r.photo}" alt="">`:`<span>${esc(r.name).charAt(0).toUpperCase()}</span>`}<div><strong>${esc(r.name)}</strong><div class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div></div></div><p>“${esc(r.comment)}”</p><div class="booking-actions">${r.status==='Pendente'?`<button class="mini-action approve" onclick="reviewStatus(${r.id},'Aprovada')">✓ Aprovar e publicar</button><button class="mini-action" onclick="reviewStatus(${r.id},'Rejeitada')">Não publicar</button>`:`<span class="status-pill status-${r.status==='Aprovada'?'confirmed':'cancelled'}">${r.status}</span>${r.status==='Rejeitada'?`<button class="mini-action" onclick="reviewStatus(${r.id},'Aprovada')">Publicar agora</button>`:`<button class="mini-action" onclick="reviewStatus(${r.id},'Rejeitada')">Retirar do site</button>`}`}</div></div>`}
function loadContent(){const c=DATA.content||{};$('#contentHero').value=c.heroHeadline||'';$('#contentHeroSub').value=c.heroSubtext||'';$('#contentCareTitle').value=c.careTitle||'';$('#contentCareText').value=c.careText||'';$('#treatmentEditors').innerHTML=(DATA.treatments||[]).map((t,i)=>`<div class="treatment-editor" data-i="${i}"><label class="switch-row">Mostrar no site <input class="te-active" type="checkbox" ${t.active?'checked':''}></label><label>Nome<input class="te-name" value="${esc(t.name)}"></label><label>Descrição<textarea class="te-desc" rows="3">${esc(t.description)}</textarea></label></div>`).join('')}$('#saveContent').onclick=()=>{const treatments=[...document.querySelectorAll('.treatment-editor')].map((el,i)=>({id:DATA.treatments[i].id,name:el.querySelector('.te-name').value,description:el.querySelector('.te-desc').value,active:el.querySelector('.te-active').checked}));saveSettings({content:{heroHeadline:$('#contentHero').value,heroSubtext:$('#contentHeroSub').value,careTitle:$('#contentCareTitle').value,careText:$('#contentCareText').value},treatments},'Pronto, Dra. Suzana! O conteúdo e os tratamentos foram atualizados.')};
function renderAll(){if(!DATA)return;const list=[...(DATA.bookings||[])].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)),pending=list.filter(b=>b.status==='Pendente'),confirmed=list.filter(b=>b.status==='Confirmado');$('#bookingList').innerHTML=list.slice(0,6).map(b=>bookingHTML(b)).join('')||'<div class="empty-state">Ainda não há movimentações.</div>';$('#agendaList').innerHTML=pending.concat(list.filter(b=>b.status!=='Pendente').slice(-3)).map(b=>bookingHTML(b,true)).join('')||'<div class="empty-state">Nenhuma solicitação nova.</div>';$('#confirmedList').innerHTML=confirmed.map(b=>bookingHTML(b,true)).join('')||'<div class="empty-state">Nenhum atendimento confirmado ainda.</div>';const today=new Date().toISOString().slice(0,10);$('#todayCount').textContent=confirmed.filter(b=>b.date===today).length;$('#futureCount').textContent=confirmed.filter(b=>b.date>=today).length;$('#pendingCount').textContent=pending.length;$('#pendingBadge').textContent=pending.length;const reviews=DATA.reviews||[],pendingR=reviews.filter(r=>r.status==='Pendente');$('#pendingReviews').textContent=pendingR.length;$('#reviewBadge').textContent=pendingR.length;$('#reviewAdminList').innerHTML=reviews.map(reviewHTML).join('')||'<div class="empty-state">Ainda não chegou nenhuma avaliação.</div>';renderAv();loadPromo();loadAbout();loadContent();const ap=DATA.appearance||{};$('#heroPosition').value=ap.heroPosition||'center';$('#heroPreview').src=ap.heroImage||'assets/suzana-hero.png';$('#heroPreview').style.objectPosition=(ap.heroPosition||'center')+' center';if($('#socialPreviewAdmin'))$('#socialPreviewAdmin').src=ap.socialPreview||('/api/social-preview?v='+Date.now())}
async function loadData(){try{DATA=await api('admin/data');renderAll()}catch(e){if(e.message==='Não autorizado.')location.reload();else alert(e.message)}}
authStatus();
