const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={selectedSlot:null,rating:0,reviewPhoto:null,data:null};
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,opt={}){const r=await fetch('/api/'+path,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Não foi possível concluir.');return d}
function resizeImage(file,max=420,quality=.72){return new Promise((resolve,reject)=>{const img=new Image(),reader=new FileReader();reader.onload=()=>img.src=reader.result;reader.onerror=reject;img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*scale),h=Math.round(img.height*scale),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality))};reader.readAsDataURL(file)})}
async function loadPublic(){try{state.data=await api('public');applyPublic()}catch(e){console.error(e)}}
function applyPublic(){const d=state.data||{},p=d.promo||{},c=d.content||{},a=d.about||{},ap=d.appearance||{};
 if(c.heroHeadline)$('#heroHeadline').textContent=c.heroHeadline;if(c.heroSubtext)$('#heroSubtext').textContent=c.heroSubtext;if(c.careTitle)$('#careTitle').textContent=c.careTitle;if(c.careText)$('#careText').textContent=c.careText;
 if(a.title)$('#aboutTitle').textContent=a.title;if(a.text)$('#aboutText').innerHTML=a.text.split('\n').filter(Boolean).map(x=>`<p>${escapeHtml(x)}</p>`).join('');
 if(ap.heroImage)$('#heroImage').src=ap.heroImage;$('#heroImage').style.objectPosition=(ap.heroPosition||'center')+' 58%';
 $('#promocao').style.display=p.active?'grid':'none';$('#promoTitle').textContent=p.title||'SOS Queda Capilar';$('#promoDescription').textContent=p.description||'';$('#promoPriceWrap').style.display=p.showPrice?'flex':'none';$('#promoOldPrice').textContent=p.oldPrice||'';$('#promoPrice').textContent=p.price||'';
 const treatments=d.treatments||[];$('#treatmentGrid').innerHTML=treatments.filter(t=>t.active).map(t=>`<article class="treatment-card"><span class="t-icon">✦</span><h3>${escapeHtml(t.name)}</h3><p>${escapeHtml(t.description)}</p><a href="#agendamento" class="preselect-service" data-service="${escapeHtml(t.name)}">Agendar avaliação →</a></article>`).join('');
 $$('.preselect-service').forEach(x=>x.onclick=()=>{if([...$('#serviceSelect').options].some(o=>o.value===x.dataset.service))$('#serviceSelect').value=x.dataset.service});renderReviews(d.reviews||[])
}
async function renderSlots(){const date=$('#dateInput').value;if(!date){$('#slots').innerHTML='<span class="muted">Escolha uma data.</span>';return}$('#slots').innerHTML='<span class="muted">Consultando horários...</span>';try{const d=await api('slots?date='+encodeURIComponent(date));$('#slots').innerHTML=d.slots.length?d.slots.map(t=>`<button class="slot" data-time="${t}" type="button">${t}</button>`).join(''):'<span class="muted">Sem horários disponíveis.</span>';state.selectedSlot=null;renderSummary();$$('.slot').forEach(btn=>btn.onclick=()=>{$$('.slot').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');state.selectedSlot=btn.dataset.time;renderSummary()})}catch(e){$('#slots').innerHTML=`<span class="muted">${escapeHtml(e.message)}</span>`}}
function renderSummary(){const date=$('#dateInput').value,service=$('#serviceSelect').value;$('#bookingSummary').innerHTML=date&&state.selectedSlot?`<strong>${escapeHtml(service)}</strong><span>${date.split('-').reverse().join('/')} às ${state.selectedSlot}</span>`:'<span>Escolha uma data e um horário.</span>'}
$('#dateInput')?.addEventListener('change',renderSlots);$('#serviceSelect')?.addEventListener('change',renderSummary);
$('#bookBtn')?.addEventListener('click',async()=>{const b={name:$('#nameInput').value.trim(),phone:$('#phoneInput').value.trim(),date:$('#dateInput').value,time:state.selectedSlot,service:$('#serviceSelect').value,notes:$('#notesInput').value.trim()};if(!b.name||!b.phone||!b.date||!b.time){$('#bookingStatus').textContent='Preencha seu nome, WhatsApp, data e selecione um horário.';$('#bookingStatus').className='booking-status error';return}try{$('#bookBtn').disabled=true;await api('bookings',{method:'POST',body:JSON.stringify(b)});$('#bookingStatus').textContent=`Pedido enviado para ${b.date.split('-').reverse().join('/')} às ${b.time}. A Dra. Suzana irá confirmar com você.`;$('#bookingStatus').className='booking-status success';$('#nameInput').value='';$('#phoneInput').value='';$('#notesInput').value='';await renderSlots()}catch(e){$('#bookingStatus').textContent=e.message;$('#bookingStatus').className='booking-status error'}finally{$('#bookBtn').disabled=false}});
function renderReviews(reviews){const approved=reviews.filter(r=>r.status==='Aprovada');const avg=approved.length?(approved.reduce((s,r)=>s+Number(r.rating),0)/approved.length).toFixed(1):'5.0';$('#ratingAverage').textContent=avg;$('#ratingCount').textContent=`${approved.length} avaliações`;$('#testimonialTrack').innerHTML=approved.map(r=>`<article class="testimonial-card">${r.photo?`<img class="review-avatar" src="${r.photo}" alt="">`:''}<div class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div><p>“${escapeHtml(r.comment)}”</p><strong>${escapeHtml(r.name)}</strong></article>`).join('')||'<div class="empty-state">As avaliações aprovadas aparecerão aqui.</div>'}
$$('#starPicker button').forEach((b,i)=>b.onclick=()=>{state.rating=i+1;$$('#starPicker button').forEach((x,j)=>x.classList.toggle('active',j<=i));$('#ratingLabel').textContent=`${state.rating} estrela${state.rating>1?'s':''}`});
$('#reviewPhoto')?.addEventListener('change',async e=>{const f=e.target.files[0];state.reviewPhoto=f?await resizeImage(f):null});
$('#sendReview')?.addEventListener('click',async()=>{const name=$('#reviewName').value.trim(),comment=$('#reviewComment').value.trim();if(!name||!comment||!state.rating){$('#reviewStatus').textContent='Preencha seu nome, comentário e escolha de 1 a 5 estrelas.';$('#reviewStatus').className='review-status error';return}try{await api('reviews',{method:'POST',body:JSON.stringify({name,comment,rating:state.rating,photo:state.reviewPhoto})});$('#reviewName').value='';$('#reviewComment').value='';$('#reviewPhoto').value='';state.rating=0;state.reviewPhoto=null;$$('#starPicker button').forEach(b=>b.classList.remove('active'));$('#ratingLabel').textContent='Selecione de 1 a 5 estrelas';$('#reviewStatus').textContent='Obrigada! Sua avaliação foi enviada e aparecerá no site após aprovação.';$('#reviewStatus').className='review-status success'}catch(e){$('#reviewStatus').textContent=e.message;$('#reviewStatus').className='review-status error'}});
$('#menuBtn')?.addEventListener('click',()=>$('#mobileNav')?.classList.toggle('open'));$$('#mobileNav a').forEach(a=>a.onclick=()=>$('#mobileNav').classList.remove('open'));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'})}}));
loadPublic();
