const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const enc=new TextEncoder();
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b)));
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function hashPassword(password,salt){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:unb64(salt),iterations:120000,hash:'SHA-256'},key,256);return b64(bits)}
async function sign(value,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',key,enc.encode(value))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function sessionCookie(user,secret){const payload=btoa(JSON.stringify({id:user.id,name:user.name,exp:Date.now()+8*60*60*1000})).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');return `${payload}.${await sign(payload,secret)}`}
async function getSession(req,secret){const cookie=req.headers.get('cookie')||'';const raw=cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith('sc_session='))?.slice(11);if(!raw)return null;const [payload,sig]=raw.split('.');if(!payload||!sig||await sign(payload,secret)!==sig)return null;try{const p=JSON.parse(atob(payload.replaceAll('-','+').replaceAll('_','/')));return p.exp>Date.now()?p:null}catch{return null}}
async function body(req){try{return await req.json()}catch{return {}}}
async function setting(DB,key,fallback=null){const r=await DB.prepare('SELECT value FROM settings WHERE key=?').bind(key).first();try{return r?JSON.parse(r.value):fallback}catch{return fallback}}
async function putSetting(DB,key,value){await DB.prepare("INSERT INTO settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(key,JSON.stringify(value)).run()}
const clean=s=>String(s??'').trim();
async function publicData(DB){const [availability,promo,content,about,appearance,treatments,reviews]=await Promise.all([setting(DB,'availability',{}),setting(DB,'promo',{}),setting(DB,'content',{}),setting(DB,'about',{}),setting(DB,'appearance',{}),DB.prepare('SELECT id,name,description,active FROM treatments ORDER BY id').all(),DB.prepare("SELECT id,name,rating,comment,photo,status,created_at AS createdAt FROM reviews WHERE status='Aprovada' ORDER BY id DESC LIMIT 30").all()]);return {availability,promo,content,about,appearance,treatments:treatments.results.map(x=>({...x,active:!!x.active})),reviews:reviews.results}}
export async function onRequest(context){
 const {request,env}=context; if(!env.DB)return json({error:'D1 não conectado. Crie o binding DB no Cloudflare.'},503);
 const url=new URL(request.url),path=(context.params.path||[]).join('/'),method=request.method.toUpperCase(); const secret=env.ADMIN_SESSION_SECRET||'CHANGE-ME-IN-CLOUDFLARE';
 try{
  if(path==='public'&&method==='GET')return json(await publicData(env.DB));
  if(path==='slots'&&method==='GET'){const date=url.searchParams.get('date');if(!date)return json({error:'Data obrigatória'},400);const av=await setting(env.DB,'availability',{}),day=new Date(date+'T12:00:00').getDay(),cfg=av[day];if(!cfg?.on)return json({slots:[]});const used=(await env.DB.prepare("SELECT time FROM bookings WHERE date=? AND status!='Cancelado'").bind(date).all()).results.map(x=>x.time);const slots=[];for(let h=Number(cfg.start.slice(0,2));h<Number(cfg.end.slice(0,2));h++){const t=String(h).padStart(2,'0')+':00';if(!used.includes(t))slots.push(t)}return json({slots})}
  if(path==='bookings'&&method==='POST'){const b=await body(request);if(!clean(b.name)||!clean(b.phone)||!clean(b.date)||!clean(b.time)||!clean(b.service))return json({error:'Preencha os campos obrigatórios.'},400);const clash=await env.DB.prepare("SELECT id FROM bookings WHERE date=? AND time=? AND status!='Cancelado'").bind(b.date,b.time).first();if(clash)return json({error:'Esse horário acabou de ser reservado. Escolha outro.'},409);const r=await env.DB.prepare("INSERT INTO bookings(service,date,time,name,phone,notes,status) VALUES(?,?,?,?,?,?,'Pendente')").bind(clean(b.service),clean(b.date),clean(b.time),clean(b.name),clean(b.phone),clean(b.notes)).run();return json({ok:true,id:r.meta.last_row_id},201)}
  if(path==='reviews'&&method==='POST'){const r=await body(request);if(!clean(r.name)||!clean(r.comment)||Number(r.rating)<1||Number(r.rating)>5)return json({error:'Preencha nome, comentário e estrelas.'},400);if(r.photo&&String(r.photo).length>700000)return json({error:'A foto ficou muito grande. Escolha uma imagem menor.'},413);await env.DB.prepare("INSERT INTO reviews(name,rating,comment,photo,status) VALUES(?,?,?,?,'Pendente')").bind(clean(r.name),Number(r.rating),clean(r.comment),r.photo||null).run();return json({ok:true},201)}
  if(path==='auth/status'&&method==='GET'){const s=await getSession(request,secret),count=(await env.DB.prepare('SELECT COUNT(*) n FROM admin_users').first()).n;return json({authenticated:!!s,hasAdmin:count>0,user:s})}
  if(path==='auth/register'&&method==='POST'){const count=(await env.DB.prepare('SELECT COUNT(*) n FROM admin_users').first()).n;if(count>0)return json({error:'O administrador já foi criado. Use Entrar.'},403);const b=await body(request);if(!clean(b.name)||!clean(b.email)||!clean(b.username)||String(b.password||'').length<8)return json({error:'Preencha tudo e use uma senha com pelo menos 8 caracteres.'},400);const salt=b64(crypto.getRandomValues(new Uint8Array(16)));const hash=await hashPassword(b.password,salt);const r=await env.DB.prepare('INSERT INTO admin_users(name,email,username,password_hash,password_salt) VALUES(?,?,?,?,?)').bind(clean(b.name),clean(b.email).toLowerCase(),clean(b.username).toLowerCase(),hash,salt).run();const token=await sessionCookie({id:r.meta.last_row_id,name:clean(b.name)},secret);return json({ok:true},200,{'set-cookie':`sc_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`})}
  if(path==='auth/login'&&method==='POST'){const b=await body(request),key=clean(b.key).toLowerCase();const u=await env.DB.prepare('SELECT * FROM admin_users WHERE username=? OR email=?').bind(key,key).first();if(!u||await hashPassword(b.password||'',u.password_salt)!==u.password_hash)return json({error:'Usuário/e-mail ou senha incorretos.'},401);const token=await sessionCookie(u,secret);return json({ok:true,name:u.name},200,{'set-cookie':`sc_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`})}
  if(path==='auth/logout'&&method==='POST')return json({ok:true},200,{'set-cookie':'sc_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'});
  const session=await getSession(request,secret);if(!session)return json({error:'Não autorizado.'},401);
  if(path==='admin/data'&&method==='GET'){const [pub,bookings,reviews]=await Promise.all([publicData(env.DB),env.DB.prepare('SELECT id,service,date,time,name,phone,notes,status,created_at AS createdAt FROM bookings ORDER BY date,time').all(),env.DB.prepare('SELECT id,name,rating,comment,photo,status,created_at AS createdAt FROM reviews ORDER BY id DESC').all()]);return json({...pub,bookings:bookings.results,reviews:reviews.results})}
  if(path.startsWith('admin/bookings/')&&method==='PATCH'){const id=Number(path.split('/').pop()),b=await body(request);if(!['Pendente','Confirmado','Cancelado'].includes(b.status))return json({error:'Status inválido'},400);await env.DB.prepare('UPDATE bookings SET status=? WHERE id=?').bind(b.status,id).run();return json({ok:true})}
  if(path.startsWith('admin/reviews/')&&method==='PATCH'){const id=Number(path.split('/').pop()),b=await body(request);if(!['Pendente','Aprovada','Rejeitada'].includes(b.status))return json({error:'Status inválido'},400);await env.DB.prepare('UPDATE reviews SET status=? WHERE id=?').bind(b.status,id).run();return json({ok:true})}
  if(path==='admin/settings'&&method==='PUT'){const b=await body(request);for(const k of ['availability','promo','content','about','appearance'])if(k in b)await putSetting(env.DB,k,b[k]);if(Array.isArray(b.treatments)){for(const t of b.treatments)await env.DB.prepare('INSERT INTO treatments(id,name,description,active) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,active=excluded.active').bind(Number(t.id),clean(t.name),clean(t.description),t.active?1:0).run()}return json({ok:true})}
  return json({error:'Rota não encontrada.'},404)
 }catch(e){console.error(e);return json({error:'Erro interno. Verifique o banco D1 e tente novamente.'},500)}
}
